# Generated by Django 6.0.4 on 2026-05-02 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'Masala Chai'), ('GR', 'Ginger Chai'), ('CD', 'Cardamom Chai'), ('TS', 'Tulsi Chai'), ('LM', 'Lemon Chai')], max_length=2)),
            ],
        ),
    ]
